### ISSUE TITLE
️refactor: AuthController API MVC 분리

### ISSUE THREAD

**Issue by oxdjww** [spon-us/SponUs-BE#293]
# Title

- 리팩토링

# TODO

- [ ] refactor `/reissue`
- [ ] refactor `/verify-email`
- [ ] refactor `/send-code`
- [ ] refactor `/verify-code`

# etc

- nothing
