### ISSUE TITLE
💚 [CI/CD] 공백 수정

### ISSUE THREAD

**Issue by seheonnn** [spon-us/SponUs-BE#8]
# Title
- CI/CD 공백 수정

# TODO
- [x] git Actions 스크립트 수정
- [x] -local, -global.yml 삭제
- [x] build.gradle 설정

# etc
- x
